// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shcsmxrtoahluxjqezgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoY3NteHJ0b2FobHV4anFlemd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Nzk3NjYsImV4cCI6MjA2OTA1NTc2Nn0.EPiibWI5ub3Zy5BT4eknKT9XN-VVz0opMJXl64DNjzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});